import { uid } from './utils.js';

function addDays(n) {
  const d = new Date();
  d.setDate(d.getDate() + n);
  d.setHours(0, 0, 0, 0);
  return d.toISOString();
}

function slot(dayOffset, startTime, endTime, capacity, booked) {
  return {
    id: uid('slot'),
    date: addDays(dayOffset),
    startTime,
    endTime,
    capacity,
    booked,
  };
}

const DESTINATIONS = [
  {
    id: 'van-thanh-mieu',
    name: 'Văn Thánh Miếu Vĩnh Long',
    category: 'bao-tang',
    interests: ['tam-linh', 'anh-dep', 'lich-su'],
    lat: 10.2496,
    lng: 105.9713,
    verifiedLocation: false,
    address: 'Phường 4, TP. Vĩnh Long',
    openingHours: '07:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.6,
    ratingCount: 128,
    isNew: false,
    recognized: true,
    recognizedReason: 'Được ghi nhận nhờ duy trì hướng dẫn tham quan miễn phí và tỷ lệ phản hồi tốt trong nhiều tháng liên tiếp trên mạng lưới demo.',
    description: 'Công trình thờ Khổng Tử và các danh nhân Nam Bộ, một trong những văn miếu cổ hiếm hoi còn lưu giữ ở miền Tây Nam Bộ.',
    story: 'Văn Thánh Miếu được xây dựng để tôn vinh truyền thống hiếu học của vùng đất Vĩnh Long, gắn liền với nhiều thế hệ nho sĩ Nam Bộ.',
    beforeYouGo: 'Trang phục lịch sự khi vào khu chính điện. Nên đi vào buổi sáng để tránh nắng gắt.',
    accessibilityNote: 'Sân rộng, lối đi bằng phẳng phù hợp xe lăn ở khu vực chính; một số bậc thềm nhỏ ở gian thờ.',
  },
  {
    id: 'chua-phat-ngoc-xa-loi',
    name: 'Chùa Phật Ngọc Xá Lợi Vĩnh Long',
    category: 'ton-giao',
    interests: ['tam-linh', 'anh-dep'],
    lat: 10.247,
    lng: 105.9702,
    verifiedLocation: false,
    address: 'Phường 4, TP. Vĩnh Long',
    openingHours: '06:00–20:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 45,
    rating: 4.7,
    ratingCount: 96,
    isNew: false,
    recognized: true,
    recognizedReason: 'Duy trì không gian đón khách thân thiện và thông tin tham quan rõ ràng.',
    description: 'Ngôi chùa nổi bật với tượng Phật ngọc lớn, không gian thoáng đãng, là điểm dừng chân tâm linh quen thuộc của người dân và du khách.',
    story: 'Chùa được nhiều thế hệ Phật tử địa phương góp công xây dựng và gìn giữ.',
    beforeYouGo: 'Giữ trật tự, ăn mặc kín đáo khi vào chính điện. Không dùng flycam khi chưa xin phép.',
    accessibilityNote: 'Sân chùa rộng, dễ di chuyển; khu chính điện có bậc thềm.',
  },
  {
    id: 'mieu-cong-than',
    name: 'Miếu Công Thần Vĩnh Long',
    category: 'bao-tang',
    interests: ['lich-su', 'tam-linh'],
    lat: 10.243,
    lng: 105.965,
    verifiedLocation: false,
    address: 'Phường Long Châu, TP. Vĩnh Long',
    openingHours: '07:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 40,
    rating: 4.4,
    ratingCount: 41,
    isNew: false,
    recognized: false,
    recognizedReason: '',
    description: 'Di tích thờ các bậc tiền hiền có công khai khẩn vùng đất Vĩnh Long xưa, mang kiến trúc gỗ truyền thống Nam Bộ.',
    story: 'Miếu lưu giữ nhiều hiện vật và sắc phong liên quan đến lịch sử khai phá vùng đất Vĩnh Long.',
    beforeYouGo: 'Nên hỏi trước nếu muốn chụp ảnh khu vực thờ chính.',
    accessibilityNote: 'Chưa có dữ liệu chi tiết về lối đi cho xe lăn; nên liên hệ trước.',
  },
  {
    id: 'vuong-quoc-gach-gom-mang-thit',
    name: 'Vương quốc gạch gốm Mang Thít',
    category: 'thu-cong',
    interests: ['thu-cong', 'anh-dep', 'trai-nghiem-tay-chan'],
    lat: 10.1682,
    lng: 106.0361,
    verifiedLocation: false,
    address: 'Huyện Mang Thít, Vĩnh Long',
    openingHours: '08:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 90,
    rating: 4.8,
    ratingCount: 212,
    isNew: false,
    recognized: true,
    recognizedReason: 'Làng nghề trăm năm được du khách đánh giá cao, duy trì hoạt động trải nghiệm ổn định cho khách ghé thăm.',
    description: 'Quần thể lò gạch, lò gốm truyền thống trải dài ven sông, từng được ví như "vương quốc" gạch gốm của miền Tây.',
    story: 'Nghề làm gạch gốm ở Mang Thít hình thành từ nguồn đất sét ven sông Cổ Chiên, từng là vùng sản xuất gạch ngói lớn của Nam Bộ.',
    beforeYouGo: 'Đường vào một số lò gạch còn nhỏ, nên đi giày thoải mái. Một số khu vực đang xuống cấp cần chú ý an toàn.',
    accessibilityNote: 'Nền đất không bằng phẳng ở một số lò gạch cũ; khu trải nghiệm chính tương đối bằng phẳng.',
  },
  {
    id: 'cu-lao-an-binh',
    name: 'Cù lao An Bình – Miệt vườn Long Hồ',
    category: 'thien-nhien',
    interests: ['thien-nhien', 'gia-dinh', 'am-thuc-dia-phuong'],
    lat: 10.2278,
    lng: 105.9836,
    verifiedLocation: false,
    address: 'Xã An Bình, huyện Long Hồ, Vĩnh Long',
    openingHours: '07:00–18:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 150,
    rating: 4.7,
    ratingCount: 305,
    isNew: false,
    recognized: true,
    recognizedReason: 'Điểm miệt vườn lâu năm, nhiều lượt khách quay lại và giới thiệu.',
    description: 'Cù lao xanh mát giữa sông Tiền với các vườn cây ăn trái, kênh rạch nhỏ và nhà vườn đón khách kiểu miền Tây.',
    story: 'Người dân cù lao gắn bó nhiều đời với nghề làm vườn, dần mở cửa đón khách tham quan trải nghiệm miệt vườn.',
    beforeYouGo: 'Nên mặc đồ gọn nhẹ, mang theo nón; một số hoạt động có thể lội nước nhẹ.',
    accessibilityNote: 'Đường trong vườn chủ yếu là lối đất/đá nhỏ, chưa phù hợp xe lăn ở nhiều đoạn.',
  },
  {
    id: 'con-chim',
    name: 'Cồn Chim – Du lịch sinh thái cộng đồng',
    category: 'thien-nhien',
    interests: ['thien-nhien', 'yen-tinh', 'am-thuc-dia-phuong'],
    lat: 9.9302,
    lng: 106.2789,
    verifiedLocation: false,
    address: 'Xã Hoà Minh, huyện Châu Thành, Trà Vinh',
    openingHours: '07:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 120,
    rating: 4.5,
    ratingCount: 58,
    isNew: true,
    recognized: false,
    recognizedReason: '',
    description: 'Mô hình du lịch sinh thái cộng đồng dựa vào rừng ngập mặn và nuôi trồng tự nhiên, còn khá mới trên mạng lưới.',
    story: 'Cộng đồng địa phương phát triển mô hình du lịch thuận thiên, hạn chế can thiệp vào hệ sinh thái rừng ngập mặn.',
    beforeYouGo: 'Nên đặt trước vì số hộ đón khách còn ít; mang theo thuốc chống côn trùng.',
    accessibilityNote: 'Di chuyển chủ yếu bằng xuồng/đường đất nhỏ, chưa phù hợp người dùng xe lăn.',
  },
  {
    id: 'chua-ang',
    name: 'Chùa Âng',
    category: 'ton-giao',
    interests: ['tam-linh', 'anh-dep', 'van-hoa-khmer'],
    lat: 9.9346,
    lng: 106.3454,
    verifiedLocation: false,
    address: 'Phường 8, TP. Trà Vinh',
    openingHours: '06:00–18:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.8,
    ratingCount: 410,
    isNew: false,
    recognized: true,
    recognizedReason: 'Di tích kiến trúc nghệ thuật tiêu biểu của văn hoá Khmer Nam Bộ, duy trì đón khách và hướng dẫn văn hoá thường xuyên.',
    description: 'Một trong những ngôi chùa Khmer cổ và đẹp nhất Nam Bộ, kiến trúc chạm khắc tinh xảo, nằm cạnh Ao Bà Om.',
    story: 'Chùa Âng gắn liền với đời sống tâm linh của cộng đồng Khmer Trà Vinh qua nhiều thế kỷ, là nơi diễn ra nhiều lễ hội truyền thống.',
    beforeYouGo: 'Trang phục kín đáo, giữ yên tĩnh trong khuôn viên chùa. Xin phép trước khi quay phim/chụp ảnh cận cảnh các vị sư.',
    accessibilityNote: 'Sân chùa rộng và khá bằng phẳng; khu chính điện có bậc thềm.',
  },
  {
    id: 'ao-ba-om',
    name: 'Ao Bà Om',
    category: 'thien-nhien',
    interests: ['thien-nhien', 'anh-dep', 'van-hoa-khmer'],
    lat: 9.9362,
    lng: 106.3427,
    verifiedLocation: false,
    address: 'Phường 8, TP. Trà Vinh',
    openingHours: '06:00–18:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.6,
    ratingCount: 389,
    isNew: false,
    recognized: true,
    recognizedReason: 'Danh thắng thiên nhiên gắn với lễ hội Ok Om Bok, được nhiều du khách ghi nhận.',
    description: 'Hồ nước tự nhiên hình chữ nhật giữa rừng cây sao, dầu cổ thụ — là danh thắng riêng biệt, không phải một ngôi chùa (nằm gần Chùa Âng).',
    story: 'Ao Bà Om gắn với truyền thuyết dân gian Khmer và là nơi tổ chức lễ hội Ok Om Bok hằng năm.',
    beforeYouGo: 'Giữ gìn vệ sinh quanh hồ, không chặt phá rễ cây cổ thụ để chụp ảnh.',
    accessibilityNote: 'Đường vòng quanh hồ khá bằng phẳng, có nhiều rễ cây nổi cần chú ý.',
  },
  {
    id: 'bao-tang-khmer-tra-vinh',
    name: 'Bảo tàng Văn hóa Dân tộc Khmer Trà Vinh',
    category: 'bao-tang',
    interests: ['van-hoa-khmer', 'lich-su'],
    lat: 9.9351,
    lng: 106.3436,
    verifiedLocation: false,
    address: 'Phường 8, TP. Trà Vinh',
    openingHours: '07:00–11:00 và 13:00–17:00, nghỉ thứ Hai',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.5,
    ratingCount: 77,
    isNew: false,
    recognized: false,
    recognizedReason: '',
    description: 'Không gian trưng bày hiện vật, nhạc cụ, trang phục và đời sống văn hoá của cộng đồng Khmer Nam Bộ.',
    story: 'Bảo tàng lưu giữ nhiều hiện vật quý về phong tục, lễ hội và nghệ thuật truyền thống Khmer.',
    beforeYouGo: 'Kiểm tra lịch nghỉ (thứ Hai) trước khi đến. Có thể đăng ký thuyết minh chuyên sâu.',
    accessibilityNote: 'Toà nhà một trệt, lối vào chính bằng phẳng.',
  },
  {
    id: 'chua-vam-ray',
    name: 'Chùa Vàm Ray',
    category: 'ton-giao',
    interests: ['tam-linh', 'anh-dep', 'van-hoa-khmer'],
    lat: 9.7186,
    lng: 106.2668,
    verifiedLocation: false,
    address: 'Huyện Trà Cú, Trà Vinh',
    openingHours: '06:00–18:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.7,
    ratingCount: 184,
    isNew: false,
    recognized: true,
    recognizedReason: 'Một trong những chùa Khmer lớn và được ghé thăm nhiều nhất khu vực.',
    description: 'Ngôi chùa Khmer theo phong cách kiến trúc Angkor với mái vàng nổi bật, quy mô lớn bậc nhất khu vực Nam Bộ.',
    story: 'Chùa được trùng tu quy mô lớn, trở thành điểm đến quen thuộc của du khách yêu thích kiến trúc Khmer.',
    beforeYouGo: 'Trang phục lịch sự; nên đến sớm để tránh nắng gắt và đông khách vào cuối tuần.',
    accessibilityNote: 'Khuôn viên rộng, sân chính bằng phẳng.',
  },
  {
    id: 'con-phung',
    name: 'Cồn Phụng',
    category: 'thien-nhien',
    interests: ['thien-nhien', 'gia-dinh', 'lich-su'],
    lat: 10.3661,
    lng: 106.3839,
    verifiedLocation: false,
    address: 'Xã Tân Thạch, huyện Châu Thành, Bến Tre',
    openingHours: '07:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 120,
    rating: 4.4,
    ratingCount: 266,
    isNew: false,
    recognized: false,
    recognizedReason: '',
    description: 'Cồn nổi giữa sông Tiền, gắn với di tích Đạo Dừa và các vườn dừa, cơ sở thủ công từ dừa.',
    story: 'Cồn Phụng từng là nơi gắn với các công trình của Đạo Dừa, nay là điểm tham quan sinh thái kết hợp làng nghề.',
    beforeYouGo: 'Một số khu vực trong Cồn Phụng có thể thu phí tham quan riêng — thông tin giá minh hoạ, chưa xác minh đầy đủ.',
    accessibilityNote: 'Di chuyển giữa các khu vực chủ yếu bằng đường bộ nhỏ và đò ngang.',
  },
  {
    id: 'lang-keo-dua-mo-cay',
    name: 'Làng nghề kẹo dừa Mỏ Cày',
    category: 'thu-cong',
    interests: ['thu-cong', 'am-thuc-dia-phuong'],
    lat: 10.2163,
    lng: 106.2681,
    verifiedLocation: false,
    address: 'Huyện Mỏ Cày Nam, Bến Tre',
    openingHours: '07:00–17:00 hằng ngày',
    priceFrom: 0,
    suggestedDurationMin: 60,
    rating: 4.5,
    ratingCount: 145,
    isNew: false,
    recognized: false,
    recognizedReason: '',
    description: 'Làng nghề truyền thống làm kẹo dừa thủ công, nổi bật với công đoạn sên kẹo và gói kẹo bằng tay.',
    story: 'Nghề làm kẹo dừa gắn liền với vùng đất trồng dừa Bến Tre, được truyền qua nhiều thế hệ gia đình.',
    beforeYouGo: 'Có thể mua kẹo dừa làm quà; hỏi trước khi chụp ảnh khu sản xuất.',
    accessibilityNote: 'Khu trưng bày bằng phẳng; khu sản xuất có bậc thềm nhỏ.',
  },
  {
    id: 'nha-vuon-co-ba',
    name: 'Nhà vườn Cô Ba (dữ liệu minh hoạ)',
    category: 'homestay',
    interests: ['am-thuc-dia-phuong', 'trai-nghiem-tay-chan', 'gia-dinh'],
    lat: 10.2295,
    lng: 105.9852,
    verifiedLocation: false,
    address: 'Xã An Bình, huyện Long Hồ, Vĩnh Long (vị trí minh hoạ)',
    openingHours: 'Theo lịch hẹn trước',
    priceFrom: 120000,
    suggestedDurationMin: 90,
    rating: 4.9,
    ratingCount: 6,
    isNew: true,
    recognized: false,
    recognizedReason: '',
    isDemoHost: true,
    hostId: 'host-co-ba',
    description: 'Hộ demo minh hoạ mô hình nhà vườn nhỏ đón khách trải nghiệm nấu ăn dân dã. Tên và hình ảnh là dữ liệu mô phỏng cho bản demo.',
    story: 'Đây là hộ dữ liệu minh hoạ, được tạo ra để trình diễn luồng Studio dành cho hộ dân mới tham gia mạng lưới.',
    beforeYouGo: 'Cần đặt lịch trước ít nhất 1 ngày vì sức chứa nhỏ.',
    accessibilityNote: 'Nhà vườn nhỏ, lối đi hẹp, chưa phù hợp xe lăn.',
  },
  {
    id: 'xuong-dan-lat-chu-sau',
    name: 'Xưởng đan lát Chú Sáu (dữ liệu minh hoạ)',
    category: 'homestay',
    interests: ['thu-cong', 'trai-nghiem-tay-chan'],
    lat: 10.171,
    lng: 106.0392,
    verifiedLocation: false,
    address: 'Huyện Mang Thít, Vĩnh Long (vị trí minh hoạ)',
    openingHours: '08:00–16:00',
    priceFrom: 80000,
    suggestedDurationMin: 75,
    rating: 4.8,
    ratingCount: 4,
    isNew: true,
    recognized: false,
    recognizedReason: '',
    isDemoHost: true,
    hostId: 'host-chu-sau',
    description: 'Hộ demo minh hoạ mô hình nghệ nhân đan lát nhỏ, mới tham gia mạng lưới. Tên và hình ảnh là dữ liệu mô phỏng cho bản demo.',
    story: 'Hộ minh hoạ để trình diễn khu vực "Mới trên mạng lưới" và luồng New Spotlight ở Studio (Phase 6).',
    beforeYouGo: 'Không gian xưởng nhỏ, nên đi theo nhóm dưới 8 người.',
    accessibilityNote: 'Lối vào xưởng có bậc thềm nhỏ.',
  },
];

const HOSTS = [
  { id: 'host-lo-gom-ba-thanh', name: 'Lò gốm Ba Thạnh', destinationId: 'vuong-quoc-gach-gom-mang-thit', isDemoHost: true, bio: 'Hộ demo minh hoạ mô hình nghệ nhân gốm truyền thống tại làng nghề Mang Thít.' },
  { id: 'host-vuon-ut-hong', name: 'Vườn trái cây Út Hồng', destinationId: 'cu-lao-an-binh', isDemoHost: true, bio: 'Hộ demo minh hoạ mô hình nhà vườn đón khách tham quan tại Cù lao An Bình.' },
  { id: 'host-co-ba', name: 'Nhà vườn Cô Ba', destinationId: 'nha-vuon-co-ba', isDemoHost: true, bio: 'Hộ demo minh hoạ, mới tham gia mạng lưới.' },
  { id: 'host-chu-sau', name: 'Xưởng đan lát Chú Sáu', destinationId: 'xuong-dan-lat-chu-sau', isDemoHost: true, bio: 'Hộ demo minh hoạ, mới tham gia mạng lưới.' },
  { id: 'host-bao-tang-khmer', name: 'Ban hướng dẫn Bảo tàng Khmer Trà Vinh', destinationId: 'bao-tang-khmer-tra-vinh', isDemoHost: false, bio: 'Đơn vị thuyết minh trực thuộc bảo tàng.' },
];

function buildExperiences() {
  return [
    {
      id: 'exp-gom-mang-thit',
      destinationId: 'vuong-quoc-gach-gom-mang-thit',
      hostId: 'host-lo-gom-ba-thanh',
      title: 'Tô màu gốm cùng nghệ nhân',
      description: 'Tự tay tô màu một sản phẩm gốm nhỏ dưới hướng dẫn của nghệ nhân làng nghề.',
      durationMin: 60,
      price: 90000,
      conditions: 'Phù hợp mọi lứa tuổi; trẻ em cần người lớn đi kèm.',
      slots: [
        slot(1, '09:00', '10:00', 12, 4),
        slot(2, '14:00', '15:00', 12, 0),
        slot(4, '09:00', '10:00', 12, 12),
      ],
    },
    {
      id: 'exp-mietvuon-anbinh',
      destinationId: 'cu-lao-an-binh',
      hostId: 'host-vuon-ut-hong',
      title: 'Chèo xuồng miệt vườn + hái trái cây',
      description: 'Chèo xuồng qua các kênh rạch nhỏ, tham quan vườn và hái trái cây theo mùa.',
      durationMin: 120,
      price: 150000,
      conditions: 'Nên mặc đồ thoải mái, có thể lội nước nhẹ. Không phù hợp người không biết bơi đi một mình.',
      slots: [
        slot(1, '08:00', '10:00', 10, 2),
        slot(1, '14:00', '16:00', 10, 6),
        slot(3, '08:00', '10:00', 10, 0),
      ],
    },
    {
      id: 'exp-banhtet-coba',
      destinationId: 'nha-vuon-co-ba',
      hostId: 'host-co-ba',
      title: 'Học gói bánh tét cùng Nhà vườn Cô Ba',
      description: 'Học cách gói và nấu bánh tét truyền thống cùng người dân địa phương.',
      durationMin: 90,
      price: 120000,
      conditions: 'Dữ liệu hộ minh hoạ — giá và lịch mang tính trình diễn.',
      slots: [
        slot(2, '09:00', '10:30', 6, 1),
        slot(5, '09:00', '10:30', 6, 0),
      ],
    },
    {
      id: 'exp-danlat-chusau',
      destinationId: 'xuong-dan-lat-chu-sau',
      hostId: 'host-chu-sau',
      title: 'Đan lát thủ công cùng Chú Sáu',
      description: 'Thử sức với kỹ thuật đan lát từ lá dừa/tre truyền thống.',
      durationMin: 75,
      price: 80000,
      conditions: 'Dữ liệu hộ minh hoạ — giá và lịch mang tính trình diễn.',
      slots: [
        slot(2, '15:00', '16:15', 8, 3),
        slot(4, '09:00', '10:15', 8, 0),
      ],
    },
    {
      id: 'exp-thuyetminh-khmer',
      destinationId: 'bao-tang-khmer-tra-vinh',
      hostId: 'host-bao-tang-khmer',
      title: 'Thuyết minh chuyên sâu văn hoá Khmer',
      description: 'Buổi thuyết minh mở rộng về lịch sử và văn hoá Khmer Nam Bộ cùng hướng dẫn viên bảo tàng.',
      durationMin: 45,
      price: 50000,
      conditions: 'Đăng ký trước tối thiểu 1 ngày.',
      slots: [
        slot(1, '09:30', '10:15', 20, 5),
        slot(3, '09:30', '10:15', 20, 0),
      ],
    },
  ];
}

function buildEvents() {
  const d = new Date();
  d.setDate(d.getDate() + 21);
  return [
    {
      id: 'ev-ok-om-bok',
      title: 'Lễ hội Ok Om Bok',
      destinationId: 'ao-ba-om',
      date: d.toISOString(),
      description: 'Lễ hội cúng trăng truyền thống của đồng bào Khmer, có đua ghe ngo và thả đèn nước.',
      conditions: 'Miễn phí tham gia khu vực lễ hội chính.',
      note: 'Ngày tổ chức thật theo âm lịch Khmer; ngày hiển thị ở đây do hệ thống demo tự tính để luôn hiển thị "sắp tới".',
    },
  ];
}

function buildReviews() {
  return [
    { id: uid('rv'), destinationId: 'van-thanh-mieu', author: 'Khách demo — Minh', rating: 5, comment: 'Không gian yên tĩnh, hướng dẫn viên nhiệt tình giải thích lịch sử.', date: addDays(-30) },
    { id: uid('rv'), destinationId: 'van-thanh-mieu', author: 'Khách demo — Thảo', rating: 4, comment: 'Đẹp và cổ kính, chỉ hơi khó tìm chỗ gửi xe.', date: addDays(-12) },
    { id: uid('rv'), destinationId: 'chua-ang', author: 'Khách demo — Huy', rating: 5, comment: 'Kiến trúc chạm khắc rất tinh xảo, nên đi kèm hướng dẫn viên để hiểu thêm văn hoá Khmer.', date: addDays(-20) },
    { id: uid('rv'), destinationId: 'chua-ang', author: 'Khách demo — Lan', rating: 5, comment: 'Không gian trang nghiêm, mọi người rất thân thiện.', date: addDays(-6) },
    { id: uid('rv'), destinationId: 'ao-ba-om', author: 'Khách demo — Phúc', rating: 4, comment: 'Cây cổ thụ rất đẹp để chụp ảnh, nên đi vào sáng sớm.', date: addDays(-15) },
    { id: uid('rv'), destinationId: 'cu-lao-an-binh', author: 'Khách demo — Ngọc', rating: 5, comment: 'Trải nghiệm chèo xuồng rất thú vị, trái cây tươi ngon.', date: addDays(-9) },
    { id: uid('rv'), destinationId: 'cu-lao-an-binh', author: 'Khách demo — Hải', rating: 4, comment: 'Phù hợp đi cùng gia đình có trẻ nhỏ.', date: addDays(-3) },
    { id: uid('rv'), destinationId: 'vuong-quoc-gach-gom-mang-thit', author: 'Khách demo — Yến', rating: 5, comment: 'Rất ấn tượng với quy mô các lò gạch cổ, nên có thêm chỗ nghỉ chân.', date: addDays(-18) },
    { id: uid('rv'), destinationId: 'nha-vuon-co-ba', author: 'Khách demo — Trang', rating: 5, comment: 'Hộ demo minh hoạ — nội dung đánh giá mang tính trình diễn.', date: addDays(-2) },
  ];
}

export const PAIR_SUGGESTIONS = [
  { id: 'pair-khmer', title: 'Nửa ngày văn hoá Khmer', destinationIds: ['chua-ang', 'ao-ba-om', 'bao-tang-khmer-tra-vinh'] },
  { id: 'pair-lang-nghe', title: 'Trải nghiệm làng nghề thủ công', destinationIds: ['vuong-quoc-gach-gom-mang-thit', 'xuong-dan-lat-chu-sau'] },
  { id: 'pair-mietvuon', title: 'Miệt vườn & ẩm thực dân dã', destinationIds: ['cu-lao-an-binh', 'nha-vuon-co-ba'] },
];

export const INTEREST_OPTIONS = [
  { value: 'tam-linh', label: 'Tâm linh' },
  { value: 'anh-dep', label: 'Ảnh đẹp' },
  { value: 'lich-su', label: 'Lịch sử' },
  { value: 'thu-cong', label: 'Thủ công' },
  { value: 'thien-nhien', label: 'Thiên nhiên' },
  { value: 'gia-dinh', label: 'Phù hợp gia đình' },
  { value: 'am-thuc-dia-phuong', label: 'Ẩm thực địa phương' },
  { value: 'trai-nghiem-tay-chan', label: 'Trải nghiệm tay chân' },
  { value: 'yen-tinh', label: 'Yên tĩnh' },
  { value: 'van-hoa-khmer', label: 'Văn hoá Khmer' },
];

export const CATEGORY_OPTIONS = [
  { value: 'thu-cong', label: 'Thủ công' },
  { value: 'am-thuc', label: 'Ẩm thực' },
  { value: 'ton-giao', label: 'Tôn giáo' },
  { value: 'le-hoi', label: 'Lễ hội' },
  { value: 'bao-tang', label: 'Bảo tàng / Di tích' },
  { value: 'thien-nhien', label: 'Thiên nhiên' },
  { value: 'homestay', label: 'Trải nghiệm tại hộ dân' },
];

export function createSeedState() {
  return {
    schemaVersion: 1,
    destinations: JSON.parse(JSON.stringify(DESTINATIONS)),
    hosts: JSON.parse(JSON.stringify(HOSTS)),
    experiences: buildExperiences(),
    slots: [],
    itineraries: [],
    bookings: [],
    bookingItems: [],
    payments: [],
    reviews: buildReviews(),
    travellerReviews: [],
    passportStamps: [],
    pointsLedger: [],
    vouchers: [],
    events: buildEvents(),
    supportTickets: [],
    proposals: [],
    moderationRecords: [],
    metrics: {},
    favorites: [],
    ui: {
      draftItinerary: [],
      notifications: [],
    },
  };
}
